### ISSUE TITLE
Please document the type of input that this script expects

### ISSUE THREAD

**Issue by yacoob** [mnemocron/TelegramChatStats#3]
Specifically, it consumes the file which is the result of wholesale export of data from Telegram Desktop. I've fed it an export of a single chat, and it choke repeatedly, expecting different file structure. 

Of course it'd be even better if you can have the script automatically detect which export it's dealing with - the single chat export is much faster to generate.

Thanks!

**Comment by mnemocron** [comment]
This feature of the Telegram client is new.
Until now the export format of a single chat was limited to `HTML` only.
Thanks for bringing it up, I will add this soon.

**Comment by mnemocron** [comment]
ok, fixed in latest commit
[add support for single chat export ](https://github.com/mnemocron/TelegramChatStats/commit/10b9ebb97bfb28f835fd05050f03dcb10525f7a3)
